
name: Adds all issues that don't include the 'bug' or 'needs-triage' labels to project board

permissions:
  repository-projects: write
  issues: write

on:
  issues:
    types:
      - labeled

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v0.3.0
        with:
          project-url: https://github.com/users/WSanders31/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}
          labeled: bug
